package models

type Items struct {
	ID                        int64  `db:"id"`
	UID                       string `db:"uid"`
	Domain                    string `db:"domain"`
	Cn                        string `db:"cn"`
	Department                string `db:"department"`
	Title                     string `db:"title"`
	Who                       string `db:"who"`
	LogonCount                int64  `db:"logon_count"`
	NumLogons7                int64  `db:"num_logons7"`
	NumShare7                 int64  `db:"num_share7"`
	NumFile7                  int64  `db:"num_file7"`
	NumAd7                    int64  `db:"num_ad7"`
	NumN7                     int64  `db:"num_n7"`
	NumLogons14               int64  `db:"num_logons14"`
	NumShare14                int64  `db:"num_share14"`
	NumFile14                 int64  `db:"num_file14"`
	NumAd14                   int64  `db:"num_ad14"`
	NumN14                    int64  `db:"num_n14"`
	NumLogons30               int64  `db:"num_logons30"`
	NumShare30                int64  `db:"num_share30"`
	NumFile30                 int64  `db:"num_file30"`
	NumAd30                   int64  `db:"num_ad30"`
	NumN30                    int64  `db:"num_n30"`
	NumLogons150              int64  `db:"num_logons150"`
	NumShare150               int64  `db:"num_share150"`
	NumFile150                int64  `db:"num_file150"`
	NumAd150                  int64  `db:"num_ad150"`
	NumN150                   int64  `db:"num_n150"`
	NumLogons365              int64  `db:"num_logons365"`
	NumShare365               int64  `db:"num_share365"`
	NumFile365                int64  `db:"num_file365"`
	NumAd365                  int64  `db:"num_ad365"`
	NumN365                   int64  `db:"num_n365"`
	HasUserPrincipalName      int64  `db:"has_user_principal_name"`
	HasMail                   int64  `db:"has_mail"`
	HasPhone                  int64  `db:"has_phone"`
	FlagDisabled              int64  `db:"flag_disabled"`
	FlagLockout               int64  `db:"flag_lockout"`
	FlagPasswordNotRequired   int64  `db:"flag_password_not_required"`
	FlagPasswordCantChange    int64  `db:"flag_password_cant_change"`
	FlagDontExpirePassword    int64  `db:"flag_dont_expire_password"`
	OwnedFiles                int64  `db:"owned_files"`
	NumMailboxes              int64  `db:"num_mailboxes"`
	NumMemberOfGroups         int64  `db:"num_member_of_groups"`
	NumMemberOfIndirectGroups int64  `db:"num_member_of_indirect_groups"`
	MemberOfIndirectGroupsIds string `db:"member_of_indirect_groups_ids"`
	MemberOfGroupsIds         string `db:"member_of_groups_ids"`
	IsAdmin                   int64  `db:"is_admin"`
	IsService                 int64  `db:"is_service"`
}
